sudo: required

services:
  - docker
language: java

before_install:
  - chmod +x gradlew

env:
  global:
    - DOCKER_IMAGE=mista123/test:1.0.0$TRAVIS_JOB_NUMBER

script:
  - gradle bootJar
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
